socialmedia/urls.py
from django.contrib import admin
from django.urls import path
from socialapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index',views.IndexView.as_view(),name="index"),
    path('reg',views.RegView.as_view(),name='register'),
    path("",views.LoginView.as_view(),name="signin"),
    path("profile",views.ProfileView.as_view(),name="profile"),
    path("post/comment/<int:id>",views.add_comment,name="addcomment"),
    path('post/<int:id>/like',views.like_view,name="like"),
    path('post/<int:id>/delete',views.delete_post,name="delete-post"),
    path('signout',views.sign_out,name="signout"),
    path('userprofile/',views.UserProfileView.as_view(),name='userprofile')
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialapp/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser

# Create your models here.

class Myuser(AbstractUser):
    phone=models.CharField(max_length=200)
    profile_pic=models.ImageField(upload_to="profilepics",null=True,blank=True)

class Photos(models.Model):
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)
    description=models.CharField(max_length=200)
    image=models.ImageField(upload_to="images")
    created_date=models.DateField(auto_now_add=True)
    is_active=models.BooleanField(default=True)
    like=models.ManyToManyField(Myuser,related_name="like") 

    def __str__(self):
        return self.image

class Comments(models.Model):
    photo=models.ForeignKey(Photos,on_delete=models.CASCADE)
    User=models.ForeignKey(Myuser,on_delete=models.CASCADE)
    comment=models.CharField(max_length=200)
    created_date=models.DateField(auto_now_add=True)

socialapp/forms.py
from django import forms
from socialapp.models import Myuser
from django.contrib.auth.forms import UserCreationForm
from socialapp.models import Photos





class RegistrationForm(UserCreationForm):
    
    class Meta():
        model=Myuser
        fields=["first_name",
        "last_name",
        "username",
        "email",
        "phone",
        "profile_pic",
        "password1",
        "password2"]

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control"}))

class PhotoForm(forms.ModelForm):
    class Meta:
        model=Photos
        fields={
            "image",
            "description"
        }
        widgets={
            "description":forms.Textarea(attrs={"class":"form-control"}),
            "image":forms.FileInput(attrs={"class":"form-select"})
        }

socialapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView,FormView,ListView
from socialapp.models import Myuser,Photos,Comments
from socialapp.forms import RegistrationForm,LoginForm,PhotoForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout


# Create your views here.

from django.views.generic import TemplateView

class IndexView(ListView):
    template_name='home.html'
    form_class=PhotoForm
    model=Photos
    success_url=reverse_lazy("index")
    context_object_name="posts"

class ProfileView(CreateView):
    template_name='profile.html'
    form_class=PhotoForm
    model=Photos
    success_url=reverse_lazy("index")

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)
    def get_queryset(self):
        return Photos.objects.all()


class RegView(CreateView):
    model=Myuser
    form_class=RegistrationForm
    template_name="registration.html"
    success_url=reverse_lazy("register") 
class LoginView(FormView):
    form_class=LoginForm
    template_name="login.html"
    def post(self,request,*args,**kw):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                return redirect("index")
            else:
                return render(request,self.template_name,{"form":form})
                

def add_comment(request,*args,**kw):
    pid=kw.get("id")
    posts=Photos.objects.get(id=pid)
    comment=request.POST.get("comment")
    Comments.objects.create(User=request.user,comment=comment,photo=posts)
    return redirect("index")

def like_view(request,*args,**kw):
    post_id=kw.get("id")
    post=Photos.objects.get(id=post_id)
    post.like.add(request.user)
    post.save()
    return redirect("index")

def delete_post(request,*args,**kw):
    post_id=kw.get("id")
    Photos.objects.get(id=post_id).delete()
    return redirect("index")


def sign_out(request,*args,**kwargs):
    logout(request)
    return redirect("signin")



class UserProfileView(ListView):
    template_name="userprofile.html"
    model=Photos
    context_object_name="photo"

    def get_queryset(self):
        return Photos.objects.all().filter(user=self.request.user)


 

socialapp/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Home - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#!">Social App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{%url 'profile'%}"><i class="fa-solid fa-plus"></i></a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'index'%}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'userprofile'%}">profile</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'signout'%}">Logout
                            
                        </a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Welcome to <p class="text-warning">Social APP!</p></h1>
                    <p class="lead mb-0">Haaai!!! Have a nice day</p>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                           {%block body_block%}

                           {%endblock%}

                        </div>
                    </div>
                    <!-- Categories widget-->
                    
        <!-- Footer-->
        <footer class="py-5 bg-dark mt-1">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
        
    </body>
</html>

socialapp/templates/home.html
{%extends 'base.html'%}
{%block body_block%}
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <form action="" method="post" enctype="multipart/form-data">

      {%csrf_token%}
      {{form.as_p}}
    </form>
  </div>
  <div class="col-4"></div>
</div>
<div class="container m-5">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">

      {%for p in posts%}

      <div class="card" style="width: 18rem;">
        {%if p.image%}
        <img src="{{p.image.url}}" class="card-img-top" alt="...">
        {%endif%}
        {%if p.user == request.user%}
        <a href="{%url 'delete-post' p.id%}" class="btn btn-danger">remove<i class="fa-solid fa-trash"></i></a>
        {%endif%}
        <div class="card-body">
          <h5 class="card-title">{{p.description}}</h5>
          <p class="card-text">{{p.created_date}}</p>
          <form action="{%url 'addcomment' p.id%}" method="post">

            {%csrf_token%}

            <div>
              <a href="{%url 'like' p.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                  fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                  <path
                    d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                </svg>
              </a>


              <a href="" class="" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false"
                aria-controls="collapseWidthExample">


                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat"
                  viewBox="0 0 16 16">
                  <path
                    d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z" />
                </svg>
              </a>

              <div>
                {{p.like.all.count}} <span>like</span>

              </div>
              <div style="min-height: 120px;">
                <div class="collapse collapse-horizontal" id="collapseWidthExample">
                  <!-- <div class="card card-body" style="width: 200px;"> -->
                  <textarea name="comment" id="" cols="30" rows="1">

                        </textarea>
                  <button type="submit" class="btn btn-primary">Add Comment</button>
                  <!-- </div> -->
                </div>
                <p>
                  <button class="btn btn-primary form-control" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    comments
                  </button>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body">
                    <ul class="list-group">
                      {%for cmt in p.comments_set.all%}
                      <li class="list-group-item">
                        <p class="card-text">
                          {{cmt.comment}}
                          posted by {{cmt.user}}on{{cmt.created_date}
                        </p>

                      </li>

                      {%endfor%}
                    </ul>
                  </div>
                </div>

              </div>


            </div>
          </form>
        </div>
      </div>
      {%endfor%}

    </div>
    <div class="col-4"></div>
  </div>
</div>



</div>
{%endblock%}

socialapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4 border border-dark m-5 mb-2">
               <div class="m-5">
                <h1 class="text-center">Social App</h1>
                <form action="" method="post" >
                    {%csrf_token%}
                    {{form.as_p}}
                    <div class="text-center">
                        <input type="submit" value="login" class="btn btn-primary ">
                        <a href="{%url 'register'%}">Register now !</a>

                    </div>
                </form>
               </div>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</body>
</html>

socialapp/templates/profile.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">

                {%csrf_token%}
                {{form.as_p}}
            <input type="submit" value="post">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
{%endblock%}

socialapp/templates/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <form action="" method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    {{form.as_p}}
                    <input type="submit">


                </form>
            </div>
        </div>

        <div class="col-4"></div>
    </div>
</body>

</html>

socialapp/templates/userprofile.html
{%extends 'base.html'%}
{%block body_block%}


<div class="container">
    <div class="row">
        <div class="col-2">
            {%if request.user.profile_pic%}
            <img class="rounded-circle" style="width: 30px; height: 30px;" src="{{request.user.profile_pic.url}}"
                alt="">
            {%endif%}
        </div>
        <div class="col-10">
            {{request.user}}
            <div>
                {{request.first_name}}
                {{request.last_name}}
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row" style="margin: 11%;">
        {%for p in photo%}
        

        <div class="card" style="width: 18rem;">
            {%if p.image%}
            <img src="{{p.image.url}}" class="card-img-top" alt="...">
            {%endif%}
            {%if p.user == request.user%}
            <a href="{%url 'delete-post' p.id%}" class="btn btn-danger">remove<i class="fa-solid fa-trash"></i></a>
            {%endif%}
            <div class="card-body">
              <h5 class="card-title">{{p.description}}</h5>
              <p class="card-text">{{p.created_date}}</p>
              <form action="{%url 'addcomment' p.id%}" method="post">
    
                {%csrf_token%}
    
                <div>
                  <a href="{%url 'like' p.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                      fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                      <path
                        d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                    </svg>
                  </a>
    
    
                  <a href="" class="" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false"
                    aria-controls="collapseWidthExample">
    
    
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat"
                      viewBox="0 0 16 16">
                      <path
                        d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z" />
                    </svg>
                  </a>
    
                  <div>
                    {{p.like.all.count}} <span>like</span>
    
                  </div>
                  <div style="min-height: 120px;">
                    <div class="collapse collapse-horizontal" id="collapseWidthExample">
                      <!-- <div class="card card-body" style="width: 200px;"> -->
                      <textarea name="comment" id="" cols="30" rows="1">
    
                            </textarea>
                      <button type="submit" class="btn btn-primary">Add Comment</button>
                      <!-- </div> -->
                    </div>
                    <p>
                      <button class="btn btn-primary form-control" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        comments
                      </button>
                    </p>
                    <div class="collapse" id="collapseExample">
                      <div class="card card-body">
                        <ul class="list-group">
                          {%for cmt in p.comments_set.all%}
                          <li class="list-group-item">
                            <p class="card-text">
                              {{cmt.comment}}
                              posted by {{cmt.user}}on{{cmt.created_date}
                            </p>
    
                          </li>
    
                          {%endfor%}
                        </ul>
                      </div>
                    </div>
    
                  </div>
    
    
                </div>
              </form>
            </div>
          </div>


        {%endfor%}


    </div>
</div>

{%endblock%}